### ISSUE TITLE
Socket.io in Multi Process Cluster

### ISSUE THREAD

**Issue by jonathan-casarrubias** [strongloop/strong-pm.io#7]
Hey there,

I have problem where I implemented socket.io in my loopback api and it works ok when you are in a single process, but once you deploy using the strongloop process manager, it creates multiple processes making the socket.io client difficult to make the handshake, this is because through the handshake process it makes several request and some of these arrive into 1 worker and other requests arrive into other workers, so the handshake fails.

There are several methods to handle this, sticky-session using nginix or the npm module to do it from node.js, but since the process cluster is built in the strong-pm I can not do anything in the app to make sticky sessions.

I have been searching a lot, but I dont see anywhere a config to make the process manager cluster work in sticky session mode.

is something that needs to be implemented? I will check the module by my own and see if I can do something then pull request, but I would like some advice here

Thanks in advanced,
Jon

**Comment by danielfbm** [comment]
@jonathan-casarrubias hi Jon, I am having the exact same issue. Although I am using Redis to solve the messaging issue, I am still dealing with how to do the sticky sessions using strong-pm. Any tips?

Thanks

**Comment by masalinas** [comment]
Did you resolve this problem?, I have the same issue ...

**Comment by masalinas** [comment]
I resolve the problem 

1) Used the redis nodem module adapter of socket.io, called socket-io-redis like like pubsub in the backend and installed the redis database

2) Force to use websockets transport protocol to my socket.io clients like this:

I used the angular module angular-socket.io to manage the socket.io clients like this:

```
$provide.factory('Socket', function (socketFactory, Context) {
            //return socketFactory();
            var socket = io({transports: ['websocket', 'flashsocket', 'htmlfile', 'xhr-polling', 'jsonp-polling', 'polling']});

            return socketFactory({ioSocket: socket});
        });
```

My backend in under a nginx proxy throw 80 port.

**Comment by jonathan-casarrubias** [comment]
I have solved this by using the socket.io mongo adapter it has worked well from a date to now... I do not use strong.pm anymore I have been using PM2 for a couple of projects and did not have this issue anymore..

Cheers!
